//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreEL2.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.pedidoscabe = new HashSet<pedidoscabe>();
        }

        [DisplayName("Cod. Cliente")]    
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese un código")]
        public string IdCliente { get; set; }

        [DisplayName("Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese un nombre")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Solo se permiten letras")]
        public string NomCliente { get; set; }

        [DisplayName("Dirección")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese una dirección")]
        public string DirCliente { get; set; }

        [DisplayName("País")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Seleccione un país")]
        public string idpais { get; set; }

        [DisplayName("Teléfono")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese un teléfono")]
        public string fonoCliente { get; set; }
    
        public virtual paises paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoscabe> pedidoscabe { get; set; }
    }
}
